version: '3'

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .db.env.example

  tesla:
    build:
      context: .
      dockerfile: Dockerfile.app
    command: tesla
    ports:
      - "80:80"
    depends_on:
      - postgres
    env_file:
      - .app.env.example